//  Lines


export function generateLines(movieName: string, translator: string, technique: string) {
    const lines = [
        `فـیـلـمی ژێـرنـووسـکـراوی کـوردی\\N{\\c&HFFFF80&} « ${movieName} »{\\c}`,
        `وەرگـێـڕان\\N{\\c&HFFFF80&}${translator}{\\c}`,
        `تـەکـنـیـک\\N{\\c&HFFFF80&}${technique}{\\c}`,
        `مـافـی ئـەم بـەرهـەمـە و ژێـرنـووسـەکـەی پـارێزراوە بۆ ماڵـپـەڕی کـوردسـەبـتایـتڵ\\N{\\c&HFFFF80&}Www.KurdSubtitle.Net{\\c}`,
    ];

    return lines
}




export function generateHeader(movieName: string) {
    return `
[Script Info]
; Script generated by Ebby.co
ScriptType: v4.00+
PlayResX: 384
PlayResY: 288
ScaledBorderAndShadow: yes
YCbCr Matrix: TV.601
PlayResX: 1920
PlayResY: 1080
Timer: 99.9500

[Aegisub Project Garbage]
Last Style Storage: Default
Video AR Value: 1.777778
Video Zoom Percent: 0.250000
Video Position: 248

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: public,Adobe Arabic,20,&H00FFFFFF,&H00853F09,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,0.7,0.7,2,10,10,10,1
Style: Name Movie,Unispace,23,&H00D9D985,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,0.7,0.7,9,10,10,10,1
Style: Public Black,Adobe Arabic,20,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,3,2,2,2,10,10,10,1
Style: Default سوچ,Segoe UI Symbol,30,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,0.5,0.3,9,10,10,20,1
Style: logo,Kurdsubtitle,23,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,0.3,0.7,2,10,10,13,1
Style: Default 1,KSB_RABAR,75,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,-1,0,0,0,100,100,0,0,1,1.4,0.8,2,10,10,30,1
Style: Default,KSB_RABAR,95,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,-1,0,0,0,100,100,0,0,1,1.4,0.8,2,10,10,35,1
Style: Default rabar 22,Rabar_022,59,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,-1,0,0,0,100,100,0,0,1,0.266667,0.466667,2,7,7,9,1
Style: Song,KSB_RABAR,90,&H0008FFFF,&H000000FF,&H00000000,&H00000000,-1,0,0,0,100,100,0,0,1,0.3,0.7,2,10,10,35,1
Style: بۆ هەر شتێک بمانەوێت زیادیکەین,Kurdsubtitle,23,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,0.3,0.7,2,10,10,15,1
Style: چەپی محمد دیبالا,KSB_RABAR,85,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,-1,0,0,0,100,100,0,0,1,1.4,0.8,4,10,10,13,1
Style: logo - Copy,Kurdsubtitle,23,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,0.3,0.7,2,10,10,13,1
Style: سکرین,KSB_RABAR,95,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,112,108,0,0,3,1.7,1,2,10,10,10,1
Style: LOGOjulaw,Kurdsubtitle,20,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,2,2,10,10,10,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:00:00.00,3:33:33.33,Default سوچ,,0,0,0,,${movieName}
Dialogue: 0,0:00:00.00,5:43:22.94,logo,,0,0,0,,{\\fnKurdsubtitle\\fs95\\a4\\c&HFFFFFF&\\bord0.519\\shad0.741\\3c&H000000&\\move(16,20.741,16,17.778,0,0)}ذ{\\4c&H000000&}\\N\\N\\N\\N
`
}




export const movedLogos = `
Dialogue: 0,0:11:05.08,0:11:20.08,LOGOjulaw,,0,0,0,,{\\fnKurdsubtitle\\fs111\\alpha&f7e&\\bord1.427\\shad0\\fad(800,800)\\fscx220.154\\fscy212\\move(31,1053.428,1891.668,21.637,971,15000)}ذ
Dialogue: 0,0:20:05.08,0:20:20.08,LOGOjulaw,,0,0,0,,{\\fnKurdsubtitle\\fs111\\alpha&f7e&\\bord1.427\\shad0\\fad(800,800)\\fscx220.154\\fscy212\\move(31,1053.428,1891.668,21.637,971,15000)}ذ
Dialogue: 0,0:29:05.08,0:29:20.08,LOGOjulaw,,0,0,0,,{\\fnKurdsubtitle\\fs111\\alpha&f7e&\\bord1.427\\shad0\\fad(800,800)\\fscx220.154\\fscy212\\move(31,1053.428,1891.668,21.637,971,15000)}ذ
Dialogue: 0,0:38:05.08,0:38:20.08,LOGOjulaw,,0,0,0,,{\\fnKurdsubtitle\\fs111\\alpha&f7e&\\bord1.427\\shad0\\fad(800,800)\\fscx220.154\\fscy212\\move(31,1053.428,1891.668,21.637,971,15000)}ذ
Dialogue: 0,0:47:05.08,0:47:20.08,LOGOjulaw,,0,0,0,,{\\fnKurdsubtitle\\fs111\\alpha&f7e&\\bord1.427\\shad0\\fad(800,800)\\fscx220.154\\fscy212\\move(31,1053.428,1891.668,21.637,971,15000)}ذ
Dialogue: 0,0:56:05.08,0:56:20.08,LOGOjulaw,,0,0,0,,{\\fnKurdsubtitle\\fs111\\alpha&f7e&\\bord1.427\\shad0\\fad(800,800)\\fscx220.154\\fscy212\\move(31,1053.428,1891.668,21.637,971,15000)}ذ
Dialogue: 0,1:08:05.08,1:08:20.08,LOGOjulaw,,0,0,0,,{\\fnKurdsubtitle\\fs111\\alpha&f7e&\\bord1.427\\shad0\\fad(800,800)\\fscx220.154\\fscy212\\move(31,1053.428,1891.668,21.637,971,15000)}ذ
Dialogue: 0,1:19:05.08,1:19:20.08,LOGOjulaw,,0,0,0,,{\\fnKurdsubtitle\\fs111\\alpha&f7e&\\bord1.427\\shad0\\fad(800,800)\\fscx220.154\\fscy212\\move(31,1053.428,1891.668,21.637,971,15000)}ذ
Dialogue: 0,1:28:05.08,1:28:20.08,LOGOjulaw,,0,0,0,,{\\fnKurdsubtitle\\fs111\\alpha&f7e&\\bord1.427\\shad0\\fad(800,800)\\fscx220.154\\fscy212\\move(31,1053.428,1891.668,21.637,971,15000)}ذ
Dialogue: 0,1:38:55.08,1:39:10.08,LOGOjulaw,,0,0,0,,{\\fnKurdsubtitle\\fs111\\alpha&f7e&\\bord1.427\\shad0\\fad(800,800)\\fscx220.154\\fscy212\\move(31,1053.428,1891.668,21.637,971,15000)}ذ
Dialogue: 0,1:48:55.08,1:49:10.08,LOGOjulaw,,0,0,0,,{\\fnKurdsubtitle\\fs111\\alpha&f7e&\\bord1.427\\shad0\\fad(800,800)\\fscx220.154\\fscy212\\move(31,1053.428,1891.668,21.637,971,15000)}ذ
Dialogue: 0,1:57:55.08,1:58:10.08,LOGOjulaw,,0,0,0,,{\\fnKurdsubtitle\\fs111\\alpha&f7e&\\bord1.427\\shad0\\fad(800,800)\\fscx220.154\\fscy212\\move(31,1053.428,1891.668,21.637,971,15000)}ذ
Dialogue: 0,2:10:10.08,2:10:25.08,LOGOjulaw,,0,0,0,,{\\fnKurdsubtitle\\fs111\\alpha&f7e&\\bord1.427\\shad0\\fad(800,800)\\fscx220.154\\fscy212\\move(31,1053.428,1891.668,21.637,971,15000)}ذ
Dialogue: 0,2:20:55.08,2:21:10.08,LOGOjulaw,,0,0,0,,{\\fnKurdsubtitle\\fs111\\alpha&f7e&\\bord1.427\\shad0\\fad(800,800)\\fscx220.154\\fscy212\\move(31,1053.428,1891.668,21.637,971,15000)}ذ
Dialogue: 0,2:31:55.08,2:32:10.08,LOGOjulaw,,0,0,0,,{\\fnKurdsubtitle\\fs111\\alpha&f7e&\\bord1.427\\shad0\\fad(800,800)\\fscx220.154\\fscy212\\move(31,1053.428,1891.668,21.637,971,15000)}ذ
Dialogue: 0,2:37:55.08,2:38:10.08,LOGOjulaw,,0,0,0,,{\\fnKurdsubtitle\\fs111\\alpha&f7e&\\bord1.427\\shad0\\fad(800,800)\\fscx220.154\\fscy212\\move(31,1053.428,1891.668,21.637,971,15000)}ذ
Dialogue: 0,2:47:55.08,2:48:10.08,LOGOjulaw,,0,0,0,,{\\fnKurdsubtitle\\fs111\\alpha&f7e&\\bord1.427\\shad0\\fad(800,800)\\fscx220.154\\fscy212\\move(31,1053.428,1891.668,21.637,971,15000)}ذ
Dialogue: 0,2:57:55.08,2:58:10.08,LOGOjulaw,,0,0,0,,{\\fnKurdsubtitle\\fs111\\alpha&f7e&\\bord1.427\\shad0\\fad(800,800)\\fscx220.154\\fscy212\\move(31,1053.428,1891.668,21.637,971,15000)}ذ
`;
